In [3]:
# !pip install nashpy
import nashpy as nash
import numpy as np

# Rock-Paper-Scissors
No nash equilibrium

In [18]:
A = np.array([[0, -1, 1], [1, 0, -1], [-1, 1, 0]])
B = - A
rps = nash.Game(A, B)
rps

# Solve for the equilibria using support enumeration
equilibria = rps.support_enumeration() # rps.vertex_enumeration() # rps.lemke_howson_enumeration()
for eq in equilibria:
    print(eq)

(array([0.33333333, 0.33333333, 0.33333333]), array([0.33333333, 0.33333333, 0.33333333]))


# matching pennies
zero sum game 

In [9]:
A = np.array([[1, -1], [-1, 1]])
matching_pennies = nash.Game(A)
matching_pennies

# calc utilities
# The utility for both players when they both play their first strategy:
sigma_r = np.array([1, 0])
sigma_c = np.array([1, 0])
print(matching_pennies[sigma_r, sigma_c])
# The utility to both players when they play uniformly randomly across both their strategies
sigma_r = np.array([0.5 , 0.5])
sigma_c = np.array([0.5 , 0.5])
print(matching_pennies[sigma_r, sigma_c])

# Solve for the equilibria using support enumeration
equilibria = matching_pennies.support_enumeration() # matching_pennies.vertex_enumeration() # matching_pennies.lemke_howson_enumeration()
for eq in equilibria:
    print(eq)

[ 1 -1]
[0. 0.]
(array([0.5, 0.5]), array([0.5, 0.5]))


# prisoners dilemma
non zero sum game 

In [10]:
A = np.array([[3, 0], [5, 1]])
B = np.array([[3, 5], [0, 1]])
prisoners_dilemma = nash.Game(A, B)
prisoners_dilemma

# calc utilities
# The utility for both players when they both play their first strategy:
sigma_r = np.array([1, 0])
sigma_c = np.array([1, 0])
print(prisoners_dilemma[sigma_r, sigma_c])

# The utility to both players when they play uniformly randomly across both their strategies
sigma_r = np.array([0.5 , 0.5])
sigma_c = np.array([0.5 , 0.5])
print(prisoners_dilemma[sigma_r, sigma_c])

# Solve for the equilibria using support enumeration
equilibria = prisoners_dilemma.support_enumeration() # prisoners_dilemma.vertex_enumeration() # prisoners_dilemma.lemke_howson_enumeration()
for eq in equilibria:
    print(eq)

[3 3]
[2.25 2.25]
(array([0., 1.]), array([0., 1.]))


# battle of the sexes
two equilibria


In [19]:
A = np.array([[3, 1], [0, 2]])
B = np.array([[2, 1], [0, 3]])
bos = nash.Game(A, B)

# Solve for the equilibria using support enumeration
equilibria = bos.support_enumeration() # bos.vertex_enumeration() # bos.lemke_howson_enumeration()
for eq in equilibria:
    print(eq)

(array([1., 0.]), array([1., 0.]))
(array([0., 1.]), array([0., 1.]))
(array([0.75, 0.25]), array([0.25, 0.75]))
